[tool.poetry]
name = "group-project"
version = "0.1.0"
description = ""
authors = ["Aradhya Tripathi <67282231+Aradhya-Tripathi@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
colabfold = {git = "https://github.com/sokrypton/ColabFold.git", rev = "2dca108", extras = ["alphafold"]}
flask = "^3.0.2"
celery = {extras = ["redis"], version = "^5.3.6"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
