[tool.poetry]
name = "group-project"
version = "0.1.0"
description = ""
authors = ["Aradhya Tripathi <67282231+Aradhya-Tripathi@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.12"
paramiko = "^3.4.0"
pyperclip = "^1.8.2"
jax = "0.4.20"
jaxlib = "0.4.20"
colabfold = {extras = ["alphafold"], version = "^1.5.5"}



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
